theme: jekyll-theme-minimal
title: Taiwan Kotlin User Group
description: Taiwan Kotlin User Group 的網站
logo: logo.png
image:
  path: logo.png
  height: 256
  width: 256
google_analytics: UA-78953126-4
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
